"""
ColorThemeGenerator — generate _generated-colors.scss from calendars.yml.

Reads exports.html.colors, finds accessible foreground colors for each
background (WCAG contrast ≥ 5.5), and writes SCSS mixins like:

  @mixin color-theme-eggplant {
    --color-text: #fff;
  }
"""

import os

from Config import Config

GENERATED_FILENAME = '_generated-colors.scss'
MIN_CONTRAST = 'AA'

_WCAG_LEVELS = {'A': 3.0, 'AA': 4.5, 'AAA': 7.0}


def _resolve_min_contrast(value):
    """Return a float contrast ratio for a numeric value or WCAG level string (A, AA, AAA)."""
    if isinstance(value, (int, float)):
        return float(value)
    key = str(value).strip().upper()
    if key in _WCAG_LEVELS:
        return _WCAG_LEVELS[key]
    raise ValueError(
        'Invalid minimum-contrast value %r. Use a number or a WCAG level: A, AA, AAA.' % value
    )


# ---------------------------------------------------------------------------
# Color math
# ---------------------------------------------------------------------------

import re as _re

_RGB_RE  = _re.compile(r'^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)(?:\s*,\s*[\d.]+)?\s*\)$', _re.I)


def _parse_color(color):
    """Parse a hex or rgb/rgba color string to (r, g, b) tuple (0–255).
    Alpha is ignored for contrast calculations.
    Accepts: #fff, #ffcc00, rgb(r,g,b), rgba(r,g,b,a), values with trailing ;"""
    if color is None:
        raise ValueError(
            'Color value is None — colors in YAML must be quoted '
            '(e.g. "#fff" not #fff, since unquoted # starts a comment)'
        )
    s = str(color).strip().rstrip(';').strip()

    m = _RGB_RE.match(s)
    if m:
        return int(m.group(1)), int(m.group(2)), int(m.group(3))

    h = s.lstrip('#').lower()
    if len(h) == 3:
        h = h[0]*2 + h[1]*2 + h[2]*2
    if len(h) != 6:
        raise ValueError('Cannot parse color: %r' % color)
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def _normalize(color):
    """Return a canonical SCSS-safe color string.
    Hex values become 6-digit lowercase #rrggbb.
    rgb/rgba values are re-emitted as rgb(r, g, b) / rgba(r, g, b, a)."""
    if color is None:
        raise ValueError(
            'Color value is None — colors in YAML must be quoted '
            '(e.g. "#fff" not #fff, since unquoted # starts a comment)'
        )
    s = str(color).strip().rstrip(';').strip()

    m = _RGB_RE.match(s)
    if m:
        # Re-emit cleanly; preserve alpha if present
        inner = s[s.index('(')+1:s.rindex(')')]
        parts = [p.strip() for p in inner.split(',')]
        fn = 'rgba' if len(parts) == 4 else 'rgb'
        return '%s(%s)' % (fn, ', '.join(parts))

    r, g, b = _parse_color(s)
    return '#%02x%02x%02x' % (r, g, b)


def _luminance(r, g, b):
    """WCAG 2.x relative luminance for 0–255 RGB."""
    def chan(c):
        c = c / 255.0
        return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4
    return 0.2126 * chan(r) + 0.7152 * chan(g) + 0.0722 * chan(b)


def _contrast(c1, c2):
    """WCAG contrast ratio between two color strings."""
    l1 = _luminance(*_parse_color(c1))
    l2 = _luminance(*_parse_color(c2))
    lighter, darker = max(l1, l2), min(l1, l2)
    return (lighter + 0.05) / (darker + 0.05)


# ---------------------------------------------------------------------------
# SCSS generation
# ---------------------------------------------------------------------------

def _build_scss(colors_config):
    """Return SCSS string for all color-theme-* mixins."""
    backgrounds = colors_config.get('backgrounds', {})
    foregrounds = colors_config.get('foregrounds', {})

    if not backgrounds:
        raise ValueError('exports.html.colors.backgrounds is empty')
    if not foregrounds:
        raise ValueError('exports.html.colors.foregrounds is empty')

    lines = [
        '// Auto-generated by ColorThemeGenerator — do not edit.',
        '// Source: config/calendars.yml > exports.html.colors',
        '@use \'sass:color\';',
        '',
    ]

    for bg_key, bg_hex in backgrounds.items():
        bg_norm = _normalize(bg_hex)
        var_lines = [
            '  --color-base: %s;' % bg_norm,
            '  --color-base-lighten: #{lighten(%s, 10%%)};' % bg_norm,
            '  --color-base-darken: #{darken(%s, 10%%)};'   % bg_norm,
            '  --color-base-shadow: #{darken(%s, 3%%)};'   % bg_norm,
        ]

        for fg_key, fg_entry in foregrounds.items():
            if isinstance(fg_entry, dict):
                fg_list = fg_entry.get('colors', [])
                min_contrast = _resolve_min_contrast(
                    fg_entry.get('minimum-contrast', MIN_CONTRAST)
                )
            else:
                fg_list = fg_entry
                min_contrast = MIN_CONTRAST

            chosen = None
            best_ratio = 0.0
            best_hex = None

            for fg_hex in fg_list:
                fg_norm = _normalize(fg_hex)
                ratio = _contrast(bg_norm, fg_norm)
                if ratio > best_ratio:
                    best_ratio = ratio
                    best_hex = fg_norm
                if ratio >= min_contrast and chosen is None:
                    chosen = fg_norm

            if chosen is None:
                raise ValueError(
                    'No accessible foreground found for background "%s" (%s) '
                    'in foreground list "%s". '
                    'Minimum contrast required: %.1f:1. '
                    'Best available: %s (%.2f:1).'
                    % (bg_key, bg_norm, fg_key, min_contrast,
                       best_hex, best_ratio)
                )

            var_lines.append('  --color-%s: %s;' % (fg_key, chosen))
            if fg_key == 'base-hover':
                var_lines.append(
                    '  --color-base-hover-translucent: #{color.adjust(%s, $alpha: -0.98)};' % chosen
                )
            if fg_key == 'focus':
                var_lines.append(
                    '  --color-focus-translucent: #{color.adjust(%s, $alpha: -0.8)};' % chosen
                )

        lines.append('@mixin color-theme-%s {' % bg_key)
        lines.extend(var_lines)
        lines.append('}')
        lines.append('')

    return '\n'.join(lines)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def writeGeneratedColors(scss_dir):
    """Generate _generated-colors.scss inside scss_dir.

    Reads config/calendars.yml, finds the first calendar with
    exports.html.colors, generates WCAG-checked SCSS mixins, and writes
    the file.  Raises ValueError if any background has no accessible
    foreground for any list.
    """
    config = Config()
    calendars = config.loadCalendars()

    html_colors = None
    for cal_name, cal_config in calendars.items():
        try:
            html_colors = cal_config['exports']['html']['colors']
            break
        except (KeyError, TypeError):
            continue

    if html_colors is None:
        raise ValueError(
            'No exports.html.colors section found in config/calendars.yml'
        )

    scss_content = _build_scss(html_colors)

    out_path = os.path.join(scss_dir, GENERATED_FILENAME)
    with open(out_path, 'w') as f:
        f.write(scss_content)

    return out_path
